version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      cache_from:
        - signSystem:latest
    image: signSystem:latest
    container_name: signSystem
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
      - ./backend/app:/app/app
    restart: unless-stopped
    networks:
      - signSystem-network

  # 可选：添加数据库服务
  # database:
  #   image: postgres:15
  #   container_name: signSystem-db
  #   environment:
  #     POSTGRES_DB: signSystem
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - signSystem-network

  # 可选：添加 Redis 缓存服务
  # redis:
  #   image: redis:7-alpine
  #   container_name: signSystem-redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - signSystem-network

networks:
  signSystem-network:
    driver: bridge

# volumes:
#   postgres_data: